### ISSUE TITLE
MapQuest Nominatim services not working

### ISSUE THREAD

**Issue by ghost** [olivere/mapquest#1]
The MapQuest Nominatim services are the services to get the data. However I wonder why following not working? Please help / guide me asap.
`http://open.mapquestapi.com/nominatim/v1/search.php?format=json&q=7580 E Big Cannon Drive,California,92808,US`

**Comment by olivere** [comment]
I'm sorry, this repository is really out of date. Feel free to send me a PR to fix the issue or use it as the blueprint for your own Golang client for the MapQuest API.
